# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9a5abd7099c744ad2fc573dfecd92d2ec3ea7430214c5059be526fbf77d17d98967d436b8b2feeb7a6797bf4078b1b6f1f54833b73c0ce829d6ee993a10ca60

test:
  secret_key_base: d0ade3a15f2527111c655632bd57d6809d1bed033a5820579594b9c1765d7e3dda811a56e68caac47bd6cc363e4a19645234e6be0cebb6ab821d4efd0744cb98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
